version: '3.9'
services:

  postgres_db:
    image: postgres:14.2
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 3s
      timeout: 10s
      retries: 2
      start_period: 2s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: [
      "sh", "-c", "cd src &&
      python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ]
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - "8001:8000"
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  postgres:
