# Use an official Python runtime as a parent image
FROM python:3.9

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory in the container
WORKDIR /app

# Install dependencies:
COPY requirements requirements/
COPY scripts scripts/
RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements/prod.txt
RUN chmod -R +x scripts

CMD ["sh", "scripts/run.sh"]
